[postgres]
url="postgres://root:123456@localhost:5432/database"


[minio]
access_key="TgNBUh5gZ0kj5KeT"
secret_key="ECU9cTmjwtgJWTf6GXHqL0JdtH8cA0Tb"
region="eu-central-1"
enpoint="http://localhost:9000"
bucket_name="test1"